/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as CreateRouteImport } from './routes/create'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as EnergyIdRouteImport } from './routes/energy.$id'
import { Route as MarketsIndexRouteImport } from './routes/markets.index'
import { Route as MarketsIdRouteImport } from './routes/markets.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const EnergyIdRoute = EnergyIdRouteImport.update({
  id: '/energy/$id',
  path: '/energy/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsIndexRoute = MarketsIndexRouteImport.update({
  id: '/markets/',
  path: '/markets/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsIdRoute = MarketsIdRouteImport.update({
  id: '/markets/$id',
  path: '/markets/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/create': typeof CreateRoute
  '/how-it-works': typeof HowItWorksRoute
  '/portfolio': typeof PortfolioRoute
  '/energy/$id': typeof EnergyIdRoute
  '/markets/$id': typeof MarketsIdRoute
  '/markets/': typeof MarketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/create': typeof CreateRoute
  '/how-it-works': typeof HowItWorksRoute
  '/portfolio': typeof PortfolioRoute
  '/energy/$id': typeof EnergyIdRoute
  '/markets/$id': typeof MarketsIdRoute
  '/markets': typeof MarketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/create': typeof CreateRoute
  '/how-it-works': typeof HowItWorksRoute
  '/portfolio': typeof PortfolioRoute
  '/energy/$id': typeof EnergyIdRoute
  '/markets/$id': typeof MarketsIdRoute
  '/markets/': typeof MarketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/create'
    | '/how-it-works'
    | '/portfolio'
    | '/energy/$id'
    | '/markets/$id'
    | '/markets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/create'
    | '/how-it-works'
    | '/portfolio'
    | '/energy/$id'
    | '/markets/$id'
    | '/markets'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/create'
    | '/how-it-works'
    | '/portfolio'
    | '/energy/$id'
    | '/markets/$id'
    | '/markets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  CreateRoute: typeof CreateRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PortfolioRoute: typeof PortfolioRoute
  EnergyIdRoute: typeof EnergyIdRoute
  MarketsIdRoute: typeof MarketsIdRoute
  MarketsIndexRoute: typeof MarketsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energy/$id': {
      id: '/energy/$id'
      path: '/energy/$id'
      fullPath: '/energy/$id'
      preLoaderRoute: typeof EnergyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets/': {
      id: '/markets/'
      path: '/markets'
      fullPath: '/markets/'
      preLoaderRoute: typeof MarketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets/$id': {
      id: '/markets/$id'
      path: '/markets/$id'
      fullPath: '/markets/$id'
      preLoaderRoute: typeof MarketsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  CreateRoute: CreateRoute,
  HowItWorksRoute: HowItWorksRoute,
  PortfolioRoute: PortfolioRoute,
  EnergyIdRoute: EnergyIdRoute,
  MarketsIdRoute: MarketsIdRoute,
  MarketsIndexRoute: MarketsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
